name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main # Agar tumhari branch ka naam 'master' hai, toh yahan master likhna

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Packages
      run: npm install

    - name: Create ZIP file
      run: zip -r deploy.zip . -x "*.git*" ".github/*"

    - name: Deploy to AWS Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: Ayush 
        zip_file: deploy.zip
